# Generated by Django 5.2 on 2025-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=10)),
                ('media_file', models.FileField(upload_to='uploads/')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('person_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField()),
            ],
        ),
    ]
